Cleaning the dataset

Importing Relevant Libraries

In [238]:
import pandas as pd
import re

Cleaning the file

Loading the csv file

In [239]:
df= pd.read_csv(r"iisermohali_faculty_raw_final_Copy.csv")
df.head()

,Name,Department,Designation,Email,Profile Link,Category,Research Area,Research Interests,Career Highlights,Awards,Publications
0,Abhik Ganguli,DMS,Assistant Professor,aganguli,https://www.iisermohali.ac.in/faculty/dms/agan...,Regular Faculty,Number Theory,"My research interests are in number theory, pa...","Ph.D., University of Chicago",NaN,Abhik Ganguli and Suneel Kumar. On the local c...
1,Abhishek Chaudhuri,DPS,Professor,abhishek,https://www.iisermohali.ac.in/faculty/dps/abhi...,Regular Faculty,Condensed Matter Physics: Soft and Biological ...,The aim of our group is to understand the phys...,"Since 2018 : Associate Professor, IISER Mohali...",NaN,Chamkor Singh and Abhishek Chaudhuri. Anomalou...
2,Adrene Freeda Dcruz,HSS,Associate Professor,adrene,https://www.iisermohali.ac.in/faculty/hss/adrene,Regular Faculty,"Science-in-theatre, Media studies, Trauma stud...",I work in the field of Science-in-theatre whic...,"Since 2015 : Assistant Professor, IISER Mohali...",Best Teacher's Award,{bibtex}adrene.bib{/bibtex}
3,Alok Maharana,DMS,Assistant Professor,maharana,https://www.iisermohali.ac.in/faculty/dms/maha...,Regular Faculty,NaN,NaN,NaN,NaN,NaN
4,Ambresh Shivaji,DPS,Associate Professor,ashivaji,https://www.iisermohali.ac.in/faculty/dps/ashi...,Regular Faculty,Theoretical High Energy Physics,"Phenomenology of Standard Model and Beyond, Hi...","2016 - 2018 : Postdoctoral Fellow, CP3, Univer...","Member, National Steering Committee, Vigyan Pr...","Mandeep Kaur, Maguni Mahakhud, Ambresh Shivaji..."

In [240]:
df_clean.describe()

,Name,Department,Designation,Email,Profile Link,Category,Research Area,Research Interests,Career Highlights,Awards,Publications,PhD Year,PhD Institution,Postdoc,Assistant Professor,Associate Professor,Professor,Other positions,Publication Available,Awards Available
count,135,135,124,135,127,135,113,114,110,81,113,98,98,58,61,24,19,103,135,135
unique,135,6,5,134,127,6,113,114,110,81,113,64,93,58,57,20,18,103,2,2
top,Abhik Ganguli,DPS,Assistant Professor,-,https://www.iisermohali.ac.in/faculty/dms/agan...,Regular Faculty,Number Theory,"My research interests are in number theory, pa...","Ph.D., University of Chicago",Best Teacher's Award,Abhik Ganguli and Suneel Kumar. On the local c...,1999 - 2005:,IIT Kanpur,"2016 - 2018: Postdoctoral Fellow, CP3, Univers...","2017 - 2023: Assistant Professor, IISER Mohali","Since 2020: Associate Professor, IISER Mohali","Since 2020: Professor, IISER Mohali","2004 - 2006: M.Sc. in Physics, IIT Kanpur, Ind...",Yes,Yes
freq,1,32,44,2,1,122,1,1,1,1,1,4,2,1,3,2,2,1,113,81

Filtering out faculty

In [241]:
df_clean = pd.read_csv("iisermohali_faculty_raw_final_Copy.csv")

print("Rows:", len(df_clean))
print(df_clean["Category"].value_counts())

Rows: 135
Category
Regular Faculty        122
Honorary Professors      5
Visiting Faculty         3
Lecturers                2
Emeritus Professors      2
Adjunct Faculty          1
Name: count, dtype: int64

In [242]:
df_clean["Department"].value_counts()

Department
DPS    32
DBS    31
DCS    26
DMS    23
EES    13
HSS    10
Name: count, dtype: int64

In [243]:
df_clean["Designation"].value_counts()

Designation
Assistant Professor        44
Associate Professor        40
Professor                  38
INSA Senior Scientist       1
INSA Honorary Scientist     1
Name: count, dtype: int64

Category

In [244]:
df_clean["Category"].value_counts()

Category
Regular Faculty        122
Honorary Professors      5
Visiting Faculty         3
Lecturers                2
Emeritus Professors      2
Adjunct Faculty          1
Name: count, dtype: int64

In [245]:
duplicates = df_clean[df_clean.duplicated(keep=False)]
print(duplicates)
df_clean = df_clean.drop_duplicates()
print("Number of duplicate rows:", df_clean.duplicated().sum())

Empty DataFrame
Columns: [Name, Department, Designation, Email, Profile Link, Category, Research Area, Research Interests, Career Highlights, Awards, Publications]
Index: []
Number of duplicate rows: 0

Extraction of faculty career data

In [246]:
print(df_clean["Career Highlights"].dropna().to_string())

0                           Ph.D., University of Chicago
1      Since 2018 : Associate Professor, IISER Mohali...
2      Since 2015 : Assistant Professor, IISER Mohali...
4      2016 - 2018 : Postdoctoral Fellow, CP3, Univer...
5      2020 - 2025 : Postdoctoral Fellow, University ...
6      Since 2021 : Member, Board of Studies for Five...
8      2007 - 2009 : Assistant Professor, Birla Insti...
9      2023 - 2023 : Assistant Professor - IIT-Palakk...
10     2025 - 2027 : Vice President (Science Promotio...
11     2015 - 2017 : Inspire Faculty at IISER Mohali ...
12     Since 2021 : Book Forum Editor for the Sage jo...
13     2023 - 2025 : Assistant Professor, Krea Univer...
14     Since 2020 : Associate Professor, IISER Mohali...
15     2004 - 2009 : Post-doctoral research, Albert E...
16     Since 2018 : Adjunct Faculty Ramakrishna Missi...
17     2019 - 2020 : Assistant Professor, Rama Univer...
18     Since 2023 : Editorial Advisory board member o...
19     2009 - 2013 : With Professor Nimrod Moiseyev, ...
20     Since 2020 : Professor, IISER Mohali 2012 - 20...
21     2012 - 2013 : Assistant Professor, Central Uni...
22     2020 - 2021 : InSAR Scientist, Geoscience Aust...
23           2004 - 2008 : PhD, University of Pittsburgh
24     Lecturer at Indiana University, Bloomington, U...
25     Since 2020  : Associate Editor, The Indian Eco...
27     Since - 2025 : Assistant Professor, IISER Moha...
29     Since 2024 : Member, Executive Council, Indian...
30     Since 2023 : Assistant Professor, Department o...
31     Since 2021 : Editor (Virology), Current Clinic...
32     2022 - 2027 : Editor, New Astronomy 2021 - 202...
33     2017 - 2023 : Assistant Professor, IISER Mohal...
34     2020 - 2020 : Assistant Professor, Indian Inst...
35     2018 - 2019: Position held: Assistant Professo...
36     Since 2025 : Assistant Professor, IISER Mohali...
37     2023 - 2025 : Editorial Board Member of the Jo...
38     2005 - 2007 : Max Planck Institute for Physics...
40     2005 - 2007 : Post-doctoral fellow, University...
41     Since 2024 : Member, Asia-Pacific NMR (APNMR) ...
42     2018 - 2023 : Assistant Professor, IISER Mohal...
44     2021 - 2025 : Ramalingaswami Fellow, Ashoka Un...
45     Since 2024 : International Committee member, A...
49     2020 - 2023 : Editor, Journal of Cell Science ...
50     Since 2025 : Professor, IISER Mohali 2018 - 20...
51     Since 2019 : Visiting Scientist, ICFO - Instit...
52     Since 2020 : Associate Professor of physics, I...
53     Since 2020 : Associate Professor, IISER Mohali...
54     Since Apr 2025 : Assistant Professor, Departme...
55     2023 - 2025 : INSPIRE Faculty Fellow, IISc Ban...
56     Since 2024 : Chairperson, National Committee f...
57     2014 - 2017: Postdoctoral fellow, IIT Bombay 2...
58     Since 2023 : Lifetime member, Astronomical Soc...
59     2014 - 2022 : Assistant Professor, IISER Mohal...
60     2007 - 2013 : Ph.D, University of Hyderabad 20...
61     2012 - 2015 : Krener Assistant Professor, Univ...
62     2022 - 2022 : Assistant Professor, IIT Dharwad...
63     Since 2023 : Assistant Professor, IISER Mohali...
64     Since 2025 : Assistant Professor, IISER Mohali...
65     2016 - 2018 : Post-doctoral research associate...
67     2007 - 2008 : Assistant Professor, IIT Roorkee...
68     2021 - 2024 : Dean of Research & Development, ...
69     2012 - 2018 : Assistant Professor, IISER Mohal...
70     2016 - 2017 : JSPS fellow, Nagoya University, ...
71     Since 2023 : Professor, IISER Mohali 2017 - 20...
72     Since 2018  : Associate professor, IISER Mohal...
73     2009 - 2011 :  Junior Research Fellow, Indian ...
74     2007 - 2011 : Postdoctoral Fellow, University ...
75     2001 - 2002 : Alexander von Humboldt fellowshi...
76     Since 2025 : Assistant Professor, Department o...
77     2010 - 2013 : Post-Doctoral Research Associate...
78     2024 : Visiting Professor, CeMIS, University o...
79     Since Oct 2023 : Head, Department of Chemical ...
80     2006 - 2009 : Assistant Professor, Professor A...
81     Since 2023 : Member of Fluorescence Society of...
82     2023 - 2025 : Editorial Board Member of ATVB 2...
83     Since 2023 : Professor, IISER Mohali, India Si...
84     2015 - 2016 : Faculty at BME,   Indian Institu...
85     Since 2019 : Associate Member, India Internati...
86     Since 2020 : Professor, IISER Mohali 2013 - 20...
87     2021 : Machine Learning Scientist, Iambic Ther...
89     Since 2023 : Associate Professor, IISER Mohali...
90     2012 - 2014 : Post-doctoral Fellow, University...
91     2022 - 2026 : Editorial Advisory Board Member,...
92     2004 - 2007 : University of Augsburg, Germany ...
93     Since 2024 : Member of the Editorial Board of ...
94     2021 - 2022 : Assistant Professor, Birla Insti...
95     2017 - 2018 : Research Associate at SALK insti...
97     2014 - 2015 : Tata Institute of Fundamental Re...
98     2024 - 2025 : One Geo 2023 - 2024 : SERB Resea...
99     Since 2020 : Associate Professor, Indian Insti...
100    2005 - 2009 : Postdoctoral Fellow, Georgia Ins...
101    Since 2014 : Member, The RNA Society (Bethesda...
103    2015 - 2018 : DST-INSPIRE Faculty, University ...
104    2013 - 2017 : Marie-Curie Post doctoral fellow...
105    Since 2010 : Professor, IISER Mohali Since 202...
107    2020 : Associate Professor in the Department o...
108    2014 - 2015 : Post Doctoral Fellow, CEA-Grenob...
109    2024 - 2027 :  Expert member, Board of Studies...
110    2009 : (Ph.D) Harish Chandra Research Institut...
111    Membership of Soft Material Research Society I...
112    Since 2020 : Associate Professor, Department o...
113    2024 : Affiliate, Madras Institute of Developm...
114    Since 2024 : Chief Examination Coordinator, Ma...
115    2009 - 2011 : Visiting Assistant Professor, Ru...
116    2024 : external expert IBSC, IIT Mandi HP Sinc...
117    Since 2024 : Deputy Editor of Global Sustainab...
118    Since 2020 : Assistant Professor, IISER Mohali...
120    2019 - 2020 : Visiting Professor, Institute fo...
121    Since 2021 : Assistant Professor, Indian Insti...
132    Since 2017 : Emeritus Professor, Department of...
133                1993 - 2010 :  Scientist, IMTECH CSIR
134    2023 - 2025 : Member (Convenor for 2023 - 2024...

In [247]:
import re

career = df_clean["Career Highlights"].dropna()

print("Total non-empty:", len(career))

print("\nContains 'Since':")
print(career.str.contains(r"\bSince\b", case=False, regex=True).sum())

print("\nContains year range:")
print(career.str.contains(r"\b\d{4}\s*[-–]\s*\d{4}\b", regex=True).sum())

print("\nContains colon:")
print(career.str.contains(":", regex=False).sum())

print("\nContains PhD:")
print(career.str.contains(r"\bPh\.?D\b", case=False, regex=True).sum())

Total non-empty: 110

Contains 'Since':
52

Contains year range:
109

Contains colon:
109

Contains PhD:
94

In [248]:

words = df_clean["Career Highlights"].fillna("").str.split()
max_words = words.str.len().max()

word_df = pd.DataFrame(
    words.tolist(),
    index=df_clean.index,
    columns=[f"Word_{i+1}" for i in range(max_words)]
)

print(word_df.to_string())

         Word_1      Word_2      Word_3         Word_4          Word_5        Word_6         Word_7           Word_8            Word_9      Word_10        Word_11       Word_12         Word_13             Word_14                     Word_15        Word_16         Word_17        Word_18        Word_19         Word_20                                                        Word_21            Word_22        Word_23              Word_24         Word_25            Word_26        Word_27       Word_28        Word_29      Word_30        Word_31       Word_32         Word_33       Word_34       Word_35                Word_36        Word_37          Word_38       Word_39      Word_40           Word_41            Word_42         Word_43              Word_44            Word_45        Word_46        Word_47              Word_48       Word_49                Word_50       Word_51       Word_52       Word_53           Word_54        Word_55                                                                 Word_56         Word_57             Word_58              Word_59             Word_60        Word_61          Word_62       Word_63             Word_64         Word_65             Word_66        Word_67         Word_68         Word_69        Word_70         Word_71        Word_72               Word_73        Word_74        Word_75        Word_76        Word_77       Word_78        Word_79       Word_80        Word_81          Word_82         Word_83          Word_84         Word_85        Word_86      Word_87      Word_88                 Word_89     Word_90                 Word_91           Word_92          Word_93       Word_94              Word_95        Word_96           Word_97        Word_98       Word_99        Word_100     Word_101       Word_102    Word_103              Word_104     Word_105      Word_106      Word_107    Word_108     Word_109       Word_110          Word_111      Word_112     Word_113     Word_114     Word_115    Word_116    Word_117      Word_118        Word_119    Word_120       Word_121             Word_122        Word_123     Word_124        Word_125     Word_126      Word_127    Word_128      Word_129     Word_130      Word_131         Word_132    Word_133          Word_134        Word_135       Word_136           Word_137     Word_138          Word_139        Word_140  Word_141     Word_142        Word_143    Word_144    Word_145        Word_146      Word_147          Word_148      Word_149     Word_150    Word_151                        Word_152       Word_153     Word_154        Word_155                                    Word_156      Word_157       Word_158    Word_159  Word_160      Word_161  Word_162    Word_163    Word_164   Word_165   Word_166   Word_167   Word_168      Word_169     Word_170     Word_171  Word_172   Word_173 Word_174         Word_175      Word_176      Word_177    Word_178      Word_179    Word_180      Word_181   Word_182     Word_183 Word_184      Word_185        Word_186     Word_187          Word_188    Word_189    Word_190   Word_191   Word_192       Word_193   Word_194     Word_195    Word_196        Word_197     Word_198       Word_199      Word_200     Word_201      Word_202     Word_203    Word_204      Word_205    Word_206       Word_207    Word_208       Word_209     Word_210          Word_211 Word_212   Word_213   Word_214 Word_215       Word_216         Word_217           Word_218        Word_219 Word_220     Word_221       Word_222 Word_223  Word_224       Word_225 Word_226                   Word_227     Word_228      Word_229 Word_230  Word_231         Word_232   Word_233 Word_234    Word_235    Word_236     Word_237      Word_238   Word_239   Word_240        Word_241    Word_242    Word_243 Word_244  Word_245    Word_246    Word_247 Word_248 Word_249        Word_250  Word_251      Word_252   Word_253            Word_254       Word_255        Word_256     Word_257 Word_258       Word_259     Word_260          Word_261 Word_262        Word_263 Word_264 Word_265  Word_266 Word_267 Word_268 Word_269 Word_270 Word_271   Word_272 Word_273 Word_274 Word_275 Word_276        Word_277 Word_278 Word_279 Word_280     Word_281   Word_282 Word_283 Word_284 Word_285 Word_286 Word_287       Word_288 Word_289   Word_290 Word_291   Word_292    Word_293 Word_294   Word_295 Word_296 Word_297 Word_298 Word_299 Word_300 Word_301 Word_302    Word_303 Word_304 Word_305 Word_306 Word_307     Word_308  Word_309 Word_310 Word_311 Word_312 Word_313 Word_314    Word_315 Word_316 Word_317 Word_318 Word_319     Word_320  Word_321 Word_322 Word_323 Word_324 Word_325 Word_326 Word_327 Word_328 Word_329 Word_330 Word_331  Word_332 Word_333 Word_334    Word_335
0        Ph.D.,  University          of        Chicago             NaN           NaN            NaN              NaN               NaN          NaN            NaN           NaN             NaN                 NaN                         NaN            NaN             NaN            NaN            NaN             NaN                                                            NaN                NaN            NaN                  NaN             NaN                NaN            NaN           NaN            NaN          NaN            NaN           NaN             NaN           NaN           NaN                    NaN            NaN              NaN           NaN          NaN               NaN                NaN             NaN                  NaN                NaN            NaN            NaN                  NaN           NaN                    NaN           NaN           NaN           NaN               NaN            NaN                                                                     NaN             NaN                 NaN                  NaN                 NaN            NaN              NaN           NaN                 NaN             NaN                 NaN            NaN             NaN             NaN            NaN             NaN            NaN                   NaN            NaN            NaN            NaN            NaN           NaN            NaN           NaN            NaN              NaN             NaN              NaN             NaN            NaN          NaN          NaN                     NaN         NaN                     NaN               NaN              NaN           NaN                  NaN            NaN               NaN            NaN           NaN             NaN          NaN            NaN         NaN                   NaN          NaN           NaN           NaN         NaN          NaN            NaN               NaN           NaN          NaN          NaN          NaN         NaN         NaN           NaN             NaN         NaN            NaN                  NaN             NaN          NaN             NaN          NaN           NaN         NaN           NaN          NaN           NaN              NaN         NaN               NaN             NaN            NaN                NaN          NaN               NaN             NaN       NaN          NaN             NaN         NaN         NaN             NaN           NaN               NaN           NaN          NaN         NaN                             NaN            NaN          NaN             NaN                                         NaN           NaN            NaN         NaN       NaN           NaN       NaN         NaN         NaN        NaN        NaN        NaN        NaN           NaN          NaN          NaN       NaN        NaN      NaN              NaN           NaN           NaN         NaN           NaN         NaN           NaN        NaN          NaN      NaN           NaN             NaN          NaN               NaN         NaN         NaN        NaN        NaN            NaN        NaN          NaN         NaN             NaN          NaN            NaN           NaN          NaN           NaN          NaN         NaN           NaN         NaN            NaN         NaN            NaN          NaN               NaN      NaN        NaN        NaN      NaN            NaN              NaN                NaN             NaN      NaN          NaN            NaN      NaN       NaN            NaN      NaN                        NaN          NaN           NaN      NaN       NaN              NaN        NaN      NaN         NaN         NaN          NaN           NaN        NaN        NaN             NaN         NaN         NaN      NaN       NaN         NaN         NaN      NaN      NaN             NaN       NaN           NaN        NaN                 NaN            NaN             NaN          NaN      NaN            NaN          NaN               NaN      NaN             NaN      NaN      NaN       NaN      NaN      NaN      NaN      NaN      NaN        NaN      NaN      NaN      NaN      NaN             NaN      NaN      NaN      NaN          NaN        NaN      NaN      NaN      NaN      NaN      NaN            NaN      NaN        NaN      NaN        NaN         NaN      NaN        NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN         NaN      NaN      NaN      NaN      NaN          NaN       NaN      NaN      NaN      NaN      NaN      NaN         NaN      NaN      NaN      NaN      NaN          NaN       NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN       NaN      NaN      NaN         NaN
1         Since        2018           :      Associate      Professor,         IISER         Mohali             2012                 -         2018              :     Assistant      Professor,               IISER                      Mohali            NaN             NaN            NaN            NaN             NaN                                                            NaN                NaN            NaN                  NaN             NaN                NaN            NaN           NaN            NaN          NaN            NaN           NaN             NaN           NaN           NaN                    NaN            NaN              NaN           NaN          NaN               NaN                NaN             NaN                  NaN                NaN            NaN            NaN                  NaN           NaN                    NaN           NaN           NaN           NaN               NaN            NaN                                                                     NaN             NaN                 NaN                  NaN                 NaN            NaN              NaN           NaN                 NaN             NaN                 NaN            NaN             NaN             NaN            NaN             NaN            NaN                   NaN            NaN            NaN            NaN            NaN           NaN            NaN           NaN            NaN              NaN             NaN              NaN             NaN            NaN          NaN          NaN                     NaN         NaN                     NaN               NaN              NaN           NaN                  NaN            NaN               NaN            NaN           NaN             NaN          NaN            NaN         NaN                   NaN          NaN           NaN           NaN         NaN          NaN            NaN               NaN           NaN          NaN          NaN          NaN         NaN         NaN           NaN             NaN         NaN            NaN                  NaN             NaN          NaN             NaN          NaN           NaN         NaN           NaN          NaN           NaN              NaN         NaN               NaN             NaN            NaN                NaN          NaN               NaN             NaN       NaN          NaN             NaN         NaN         NaN             NaN           NaN               NaN           NaN          NaN         NaN                             NaN            NaN          NaN             NaN                                         NaN           NaN            NaN         NaN       NaN           NaN       NaN         NaN         NaN        NaN        NaN        NaN        NaN           NaN          NaN          NaN       NaN        NaN      NaN              NaN           NaN           NaN         NaN           NaN         NaN           NaN        NaN          NaN      NaN           NaN             NaN          NaN               NaN         NaN         NaN        NaN        NaN            NaN        NaN          NaN         NaN             NaN          NaN            NaN           NaN          NaN           NaN          NaN         NaN           NaN         NaN            NaN         NaN            NaN          NaN               NaN      NaN        NaN        NaN      NaN            NaN              NaN                NaN             NaN      NaN          NaN            NaN      NaN       NaN            NaN      NaN                        NaN          NaN           NaN      NaN       NaN              NaN        NaN      NaN         NaN         NaN          NaN           NaN        NaN        NaN             NaN         NaN         NaN      NaN       NaN         NaN         NaN      NaN      NaN             NaN       NaN           NaN        NaN                 NaN            NaN             NaN          NaN      NaN            NaN          NaN               NaN      NaN             NaN      NaN      NaN       NaN      NaN      NaN      NaN      NaN      NaN        NaN      NaN      NaN      NaN      NaN             NaN      NaN      NaN      NaN          NaN        NaN      NaN      NaN      NaN      NaN      NaN            NaN      NaN        NaN      NaN        NaN         NaN      NaN        NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN         NaN      NaN      NaN      NaN      NaN          NaN       NaN      NaN      NaN      NaN      NaN      NaN         NaN      NaN      NaN      NaN      NaN          NaN       NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN       NaN      NaN      NaN         NaN
2         Since        2015           :      Assistant      Professor,         IISER         Mohali             2006                 -         2011              :          PhD,             IIT              Kanpur                         NaN            NaN             NaN            NaN            NaN             NaN                                                            NaN                NaN            NaN                  NaN             NaN                NaN            NaN           NaN            NaN          NaN            NaN           NaN             NaN           NaN           NaN                    NaN            NaN              NaN           NaN          NaN               NaN                NaN             NaN                  NaN                NaN            NaN            NaN                  NaN           NaN                    NaN           NaN           NaN           NaN               NaN            NaN                                                                     NaN             NaN                 NaN                  NaN                 NaN            NaN              NaN           NaN                 NaN             NaN                 NaN            NaN             NaN             NaN            NaN             NaN            NaN                   NaN            NaN            NaN            NaN            NaN           NaN            NaN           NaN            NaN              NaN             NaN              NaN             NaN            NaN          NaN          NaN                     NaN         NaN                     NaN               NaN              NaN           NaN                  NaN            NaN               NaN            NaN           NaN             NaN          NaN            NaN         NaN                   NaN          NaN           NaN           NaN         NaN          NaN            NaN               NaN           NaN          NaN          NaN          NaN         NaN         NaN           NaN             NaN         NaN            NaN                  NaN             NaN          NaN             NaN          NaN           NaN         NaN           NaN          NaN           NaN              NaN         NaN               NaN             NaN            NaN                NaN          NaN               NaN             NaN       NaN          NaN             NaN         NaN         NaN             NaN           NaN               NaN           NaN          NaN         NaN                             NaN            NaN          NaN             NaN                                         NaN           NaN            NaN         NaN       NaN           NaN       NaN         NaN         NaN        NaN        NaN        NaN        NaN           NaN          NaN          NaN       NaN        NaN      NaN              NaN           NaN           NaN         NaN           NaN         NaN           NaN        NaN          NaN      NaN           NaN             NaN          NaN               NaN         NaN         NaN        NaN        NaN            NaN        NaN          NaN         NaN             NaN          NaN            NaN           NaN          NaN           NaN          NaN         NaN           NaN         NaN            NaN         NaN            NaN          NaN               NaN      NaN        NaN        NaN      NaN            NaN              NaN                NaN             NaN      NaN          NaN            NaN      NaN       NaN            NaN      NaN                        NaN          NaN           NaN      NaN       NaN              NaN        NaN      NaN         NaN         NaN          NaN           NaN        NaN        NaN             NaN         NaN         NaN      NaN       NaN         NaN         NaN      NaN      NaN             NaN       NaN           NaN        NaN                 NaN            NaN             NaN          NaN      NaN            NaN          NaN               NaN      NaN             NaN      NaN      NaN       NaN      NaN      NaN      NaN      NaN      NaN        NaN      NaN      NaN      NaN      NaN             NaN      NaN      NaN      NaN          NaN        NaN      NaN      NaN      NaN      NaN      NaN            NaN      NaN        NaN      NaN        NaN         NaN      NaN        NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN         NaN      NaN      NaN      NaN      NaN          NaN       NaN      NaN      NaN      NaN      NaN      NaN         NaN      NaN      NaN      NaN      NaN          NaN       NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN       NaN      NaN      NaN         NaN

In [249]:

import pandas as pd

# A new entry starts with:
# Since 2018 :
# Since Apr 2025 :
# 2016 - 2018 :
# 2024 :
# 2018-2019 :

start_pattern = r'(?:Since\s+(?:(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\s+)?\d{4}|\d{4}(?:\s*[-–]\s*\d{4})?)\s*:'

rows = []

for idx, text in df_clean["Career Highlights"].dropna().items():

    
    matches = list(re.finditer(start_pattern, text))

    for i, match in enumerate(matches):

        
        start = match.end()

        
        if i + 1 < len(matches):
            end = matches[i + 1].start()
        else:
            end = len(text)

        career = text[start:end].strip()

        rows.append({
            "Name": df.loc[idx, "Name"],
            "Period": match.group().replace(" :", ":"),
            "Career": career
        })

career_extracted = pd.DataFrame(rows)

print(career_extracted.to_string())

                            Name           Period                                                                                                                                                                                                                                                                                                                             Career
0             Abhishek Chaudhuri      Since 2018:                                                                                                                                                                                                                                                                                                  Associate Professor, IISER Mohali
1             Abhishek Chaudhuri     2012 - 2018:                                                                                                                                                                                                                                                                                                  Assistant Professor, IISER Mohali
2            Adrene Freeda Dcruz      Since 2015:                                                                                                                                                                                                                                                                                                  Assistant Professor, IISER Mohali
3            Adrene Freeda Dcruz     2006 - 2011:                                                                                                                                                                                                                                                                                                                    PhD, IIT Kanpur
4                Ambresh Shivaji     2016 - 2018:                                                                                                                                                                                                                                                                Postdoctoral Fellow, CP3, Université catholique de Louvain, Belgium
5                Ambresh Shivaji     2015 - 2016:                                                                                                                                                                                                                                                                                 Postdoctoral Fellow, INFN, Sezione di Pavia, Italy
6                Ambresh Shivaji     2012 - 2015:                                                                                                                                                                                                                                                                                          Postdoctoral Fellow, HRI Allahabad, India
7                Ambresh Shivaji     2006 - 2012:                                                                                                                                                                                                                                                                          Ph.D. in Physics, Institute of Physics Bhubaneswar, India
8                Ambresh Shivaji     2004 - 2006:                                                                                                                                                                                                                                                                                                M.Sc. in Physics, IIT Kanpur, India
9                Ambresh Shivaji     2000 - 2003:                                                                                                                                                                                                                                                        B.Sc. in Physics & Mathematics, Dr. R.M.L. Avadh University, Ayodhya, India
10                     Amar Deep     2020 - 2025:                                                                                                                                                                                                                                                                     Postdoctoral Fellow, University of California, San Diego, USA.
11                     Amar Deep     2014 - 2019:                                                                                                                                                                                                                                             Ph.D. (Structural Biology), CSIR-Institute of Microbial Technology, Chandigarh, India.
12                     Amar Deep     2011 - 2013:                                                                                                                                                                                                                                                                      M.Sc. (Human Genomics), Panjab University, Chandigarh, India.
13                     Amar Deep     2008 - 2011:                                                                                                                                                                          B.Sc. (Honours) Biotechnology, Himachal Pradesh University, Shimla, India. (College: Himachal Institute of Life Sciences, Paonta Sahib, Himachal Pradesh)
14              Amit Kulshrestha      Since 2021:                                                                                                                                                                                                                                            Member, Board of Studies for Five Year Integrated Program, Punjabi University, Patiala.
15              Amit Kulshrestha      Since 2022:                                                                                                                                                                                                                                                                Member of the Vision Group, Pushpa Gujral Science City, Kapurthala.
16              Amit Kulshrestha     2007 - 2008:                                                                                                                                                                                                                                                                  Visiting Scientist, Indian Statistical Institute, Bangalore/Delhi
17              Amit Kulshrestha     2005 - 2007:                                                                                                                                                                                                                                                                     Postdoctoral fellow, University catholique de Louvain, Belgium
18              Amit Kulshrestha     1999 - 2005:                                                                                                                                                                                                                                                                                PhD, Tata Institute of Fundamental Research, Mumbai
19       Angshuman Roy Choudhury     2007 - 2009:                                                                                                                                                                                                                                                             Assistant Professor, Birla Institute of Technology and Science, Pilani
20       Angshuman Roy Choudhury     2004 - 2007:                                                                                                                                                                                                                                                                      Post doctoral Research Associate, Unievrsity of Liverpool, UK
21       Angshuman Roy Choudhury     1999 - 2004:                                                                                                                                                                                                                                                                              Ph. D., Indian Institute of Science, Bangalore, India
22       Angshuman Roy Choudhury     1997 - 1999:                                                                                                                                                                                                                                                                                            M. Sc in Chemistry, Calcutta University
23       Angshuman Roy Choudhury     1994 - 1997:                                                                                                                                                                                                                                                                                      B. Sc. (Chemistry Hons.), Calcutta University
24            Anil Kumar Dasanna     2023 - 2023:                                                                                                                                                                                                                                                                                                 Assistant Professor - IIT-Palakkad
25            Anil Kumar Dasanna     2021 – 2023:                                                                                                                                                                                                                                                                               Postdoctoral Scientist, Saarland University, Germany
26            Anil Kumar Dasanna     2018 – 2021:                                                                                                                                                                                                                                                                         Postdoctoral Scientist, Forschungszentrum Juelich, Germany
27            Anil Kumar Dasanna     2013 – 2018:                                                                                                                                                                                                                                                                             Postdoctoral Scientist, Heidelberg University, Germany
28            Anil Kumar Dasanna     2010 - 2013:                                                                                                                                                                                                                                                       PhD in Biophysics, Université Toulouse III - Paul Sabatier, Toulouse, France
29            Anil Kumar Dasanna     2007 - 2009:                                                                                                                                                                                                                                                                      M.Sc in Physics, Indian Institute of Technology-Madras, India
30           Anil Kumar Tripathi     2025 - 2027:                                                                                                                                                                                                                                              Vice President (Science Promotion), Indian National Science Academy (INSA), New Delhi
31           Anil Kumar Tripathi     2025 - 2027:                                                                                                                                                                                                                                                                       Member, Council, Indian Academy of Science (IASc), Bengaluru
32           Anil Kumar Tripathi     Since 2024 :                                                                                                                                                                                                                                                                                                             Director, IISER Mohali
33           Anil Kumar Tripathi     2022 - 2024:                                                                                                                                                                                                                                                Convener, Sectional Committee, Plant Sciences, Indian Academy of Science, Bengaluru
34           Anil Kumar Tripathi     2023 - 2025:                                                                                                                                                                                                                                            Convener/ Member, Sectional Committee, General Biology, Indian National Science Academy
35           Anil Kumar Tripathi     2021 - 2024:                                                                                                                                                                                                                                                                        Chairman, Plant Science Research Committee, CSIR, New Delhi
36           Anil Kumar Tripathi     2021 - 2024:                                                                                                                                                                                                                                                                                             Member, Court, University of Hyderabad
37           Anil Kumar Tripathi     2021 - 2024:                                                                                                                                                                                                                                                        Member, Governing Body, National Institute of Plant Genome Research (NIPGR)
38           Anil Kumar Tripathi     2019 - 2022:                                                                                                                                                                                                                                                                                           Member, Governing Body, NIPER, Raebareli
39           Anil Kumar Tripathi     2018 - 2019:                                                                                                                                                                                                                                                              Member, Council, National Academy of Sciences India (NASI), Prayagraj
40           Anil Kumar Tripathi     2017 - 2019:                                                                                                                                                                                                                                                                  Member, Research Council, Agharkar Research Institute (DST), Pune
41           Anil Kumar Tripathi     2017 - 2019:                                                                                                                                                                                                                                                                             Member, Research Council, CSIR-NIIST, Thiruvanantpuram
42           Anil Kumar Tripathi     2016 - 2019:                                                                                                                                                                                                                                                                     Member, INSA Sectional Committee IX: Microbiology & Immunology
43           Anil Kumar Tripathi            2016:                                                                                                                                                                                                                                                                                       Member, CSIR Governing Body and CSIR Society
44           Anil Kumar Tripathi     2019 - 2014:                                                                                                                                                                                                                                                                           Director, Institute of Science, Banaras Hindu University
45           Anil Kumar Tripathi     2019 - 2023:                                                                                                                                                                                                                                                                                   Coordinator, DST-SATHI, Banaras Hindu University
46           Anil Kumar Tripathi     2019 - 2024:                                                                                                                                                                                                                                                                               Coordinator, BIRAC-BioNEST, Banaras Hindu University
47           Anil Kumar Tripathi     2014 - 2019:                                                                                                                                                                                                                                                          Director, Central Institute of Medicinal and Aromatic Plants (CSIR-CIMAP)
48           Anil Kumar Tripathi     2017 - 2029:                                                                                                                                                                                                                                                                                               Mission Director, CSIR Aroma Mission
49           Anil Kumar Tripathi     2013 - 2014:                                                                                                                                                                                                                                                      Coordinator, DBT-BHU Interdisciplinary School of Life Sciences, BHU, Varanasi
50           Anil Kumar Tripathi     2008 - 2011:                                                                                                                                                                                                                                                                                        Coordinator, Centre for Bioinformatics, BHU
51           Anil Kumar Tripathi     2007 - 2010:                                                                                                                                                                                                                                                                                          Coordinator, School of Biotechnology, BHU

In [250]:

career_summary = df_clean[["Name"]].copy()

phd_mask = career_extracted["Career"].str.contains(
    r"\bPh\.?\s*D\b|\bPhD\b",
    case=False,
    regex=True,
    na=False
)


phd_year = (
    career_extracted[phd_mask]
    .groupby("Name")["Period"]
    .apply(lambda x: " | ".join(x))
    .rename("PhD Year")
)

def get_phd_institution(text):
    text = re.sub(
        r"\bPh\.?\s*D\b\.?",
        "",
        text,
        flags=re.IGNORECASE
    )

    text = re.sub(
        r"\b(in|of)\s+(Physics|Biology|Chemistry|Mathematics|Science|Engineering)\b",
        "",
        text,
        flags=re.IGNORECASE
    )

    return text.strip(" ,.-")


phd_institution = (
    career_extracted[phd_mask]
    .assign(
        Institution=lambda x:
        x["Career"].apply(get_phd_institution)
    )
    .groupby("Name")["Institution"]
    .apply(lambda x: " | ".join(x))
    .rename("PhD Institution")
)


def classify_position(text):

    text_lower = text.lower()

    if "postdoctoral" in text_lower or "post-doctoral" in text_lower:
        return "Postdoc"

    elif "assistant professor" in text_lower:
        return "Assistant Professor"

    elif "associate professor" in text_lower:
        return "Associate Professor"

    elif re.search(r"\bprofessor\b", text_lower):
        return "Professor"

    else:
        return "Other positions"


career_extracted["Position Type"] = (
    career_extracted.apply(
        lambda row: (
            "PhD"
            if phd_mask.loc[row.name]
            else classify_position(row["Career"])
        ),
        axis=1
    )
)

def combine_entries(group):

    return " | ".join(
        group["Period"] + " " + group["Career"]
    )
postdoc = (
    career_extracted[
        career_extracted["Position Type"] == "Postdoc"
    ]
    .groupby("Name")
    .apply(combine_entries, include_groups=False)
    .rename("Postdoc")
)

assistant_prof = (
    career_extracted[
        career_extracted["Position Type"] == "Assistant Professor"
    ]
    .groupby("Name")
    .apply(combine_entries, include_groups=False)
    .rename("Assistant Professor")
)

associate_prof = (
    career_extracted[
        career_extracted["Position Type"] == "Associate Professor"
    ]
    .groupby("Name")
    .apply(combine_entries, include_groups=False)
    .rename("Associate Professor")
)

professor = (
    career_extracted[
        career_extracted["Position Type"] == "Professor"
    ]
    .groupby("Name")
    .apply(combine_entries, include_groups=False)
    .rename("Professor")
)

other_positions = (
    career_extracted[
        career_extracted["Position Type"] == "Other positions"
    ]
    .groupby("Name")
    .apply(combine_entries, include_groups=False)
    .rename("Other positions")
)

career_summary = (
    career_summary
    .merge(phd_year, on="Name", how="left")
    .merge(phd_institution, on="Name", how="left")
    .merge(postdoc, on="Name", how="left")
    .merge(assistant_prof, on="Name", how="left")
    .merge(associate_prof, on="Name", how="left")
    .merge(professor, on="Name", how="left")
    .merge(other_positions, on="Name", how="left")
)


print(career_summary.to_string())

                                 Name                     PhD Year                                                                                                                                                          PhD Institution                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Postdoc                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Assistant Professor                                                                                                                     Associate Professor                                                                                                                                                                                                                                                                                                                                                                                                              Professor                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 Other positions
0                       Abhik Ganguli                          NaN                                                                                                                                                                      NaN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        NaN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  NaN                                                                                                                                     NaN                                                                                                                                                                                                                                                                                                                                                                                                                    NaN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             NaN
1                  Abhishek Chaudhuri                          NaN                                                                                                                                                                      NaN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        NaN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       2012 - 2018: Assistant Professor, IISER Mohali                                                                                           Since 2018: Associate Professor, IISER Mohali                                                                                                                                                                                                                                                                                                                                                                                                                    NaN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             NaN
2                 Adrene Freeda Dcruz                 2006 - 2011:                                                                                                                                                               IIT Kanpur                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        NaN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Since 2015: Assistant Professor, IISER Mohali                                                                                                                                     NaN                                                                                                                                                                                                                                                                                                                                                                                                                    NaN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             NaN
3                       Alok Maharana                          NaN                                                                                                                                                                      NaN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        NaN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  NaN                                                                                                                                     NaN                                                                                                                                                                                                                                                                                                                                                                                                                    NaN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             NaN

In [251]:
research_summary = df_clean[["Name"]].copy()

In [252]:
research_summary["Publication Available"] = (
    df_clean["Publications"]
    .fillna("")
    .astype(str)
    .str.strip()
    .ne("")
    .map({True: "Yes", False: "No"})
)

research_summary["Awards Available"] = (
    df_clean["Awards"]
    .fillna("")
    .astype(str)
    .str.strip()
    .ne("")
    .map({True: "Yes", False: "No"})
)

In [253]:
print(
    research_summary[
        ["Name", "Publication Available", "Awards Available"]
    ].to_string(index=False)
)

                            Name Publication Available Awards Available
                   Abhik Ganguli                   Yes               No
              Abhishek Chaudhuri                   Yes               No
             Adrene Freeda Dcruz                   Yes              Yes
                   Alok Maharana                    No               No
                 Ambresh Shivaji                   Yes              Yes
                       Amar Deep                   Yes              Yes
                Amit Kulshrestha                   Yes              Yes
               Ananth Venkatesan                    No               No
         Angshuman Roy Choudhury                   Yes               No
              Anil Kumar Dasanna                   Yes               No
             Anil Kumar Tripathi                   Yes              Yes
                    Anoop Ambili                   Yes              Yes
                     Anu Sabhlok                   Yes              Yes
                   Arghya Mondal                   Yes              Yes
                 Arijit Kumar De                   Yes              Yes
            Arunika Mukhopadhaya                   Yes              Yes
                          Arvind                   Yes              Yes
             Arvind Kumar Shakya                   Yes              Yes
                   Baerbel Sinha                   Yes              Yes
           Balanarayan Pananghat                   Yes              Yes
                  Chanchal Kumar                   Yes               No
       Chandrakant Sharma Aribam                   Yes               No
               Chandrakanta Ojha                   Yes              Yes
            Chetan Tukaram Balwe                   Yes               No
               Debashis Adhikari                   Yes              Yes
                   Debdulal Saha                   Yes              Yes
            Dipanjan Chakraborty                    No               No
               Eswaraiah Chakali                   Yes              Yes
                    Goutam Sheet                    No               No
           Harvinder Kaur Jassal                   Yes               No
                  Hasan Mohammad                   Yes              Yes
               Indranil Banerjee                   Yes              Yes
             Jasjeet Singh Bagla                   Yes              Yes
                     Jino George                   Yes              Yes
                  Jogender Singh                   Yes              Yes
                  Jotsaroop Kaur                    No               No
                Jyotima Kanaujia                   Yes              Yes
            Kausik Chattopadhyay                   Yes              Yes
               Kamal Priya Singh                   Yes              Yes
                 K. P. Yogendran                    No               No
               K. R. Shamasundar                   Yes               No
                    Kavita Dorai                   Yes              Yes
                  Kinjalk Lochan                   Yes              Yes
         Krishnendu Gongopadhyay                   Yes               No
                 Kritika M. Garg                   Yes              Yes
               Kuduva R. Vignesh                   Yes              Yes
                  Kuljeet Sandhu                    No               No
                   Lingaraj Sahu                   Yes               No
                 Lolitika Mandal                    No               No
                    Mahak Sharma                   Yes              Yes
                  Mahender Singh                   Yes              Yes
            Manabendra Nath Bera                   Yes              Yes
                    Mandip Singh                   Yes              Yes
                    Manjari Jain                   Yes               No
                     Manoj Kumar                   Yes              Yes
                     Mihir Sheth                   Yes               No
                      N G Prasad                   Yes              Yes
            Neeraja Sahasrabudhe                   Yes               No
                 Pankaj Kushwaha                   Yes              Yes
                Parth R. Chauhan                   Yes               No
                   Philose Koshy                   Yes               No
                   Pranab Sardar                   Yes               No
                   Prasenjit Das                   Yes              Yes
                   Pritam Mondal                   Yes              Yes
                         Pritika                   Yes               No
                 Priyakumari C P                   Yes               No
           Purnananda Guptasarma                    No               No
             Ramesh Ramachandran                   Yes              Yes
                 R. Vijaya Anand                   Yes              Yes
                    Rachna Chaba                   Yes              Yes
                   Raj Kumar Roy                   Yes              Yes
                    Rajeev Kapri                   Yes              Yes
             Rajesh Ramachandran                   Yes              Yes
                     Raju Attada                   Yes              Yes
                       Ram Yadav                   Yes              Yes
           Ramandeep Singh Johal                   Yes               No
          Ravi Sureshbhai Devani                   Yes              Yes
          Rhitoban Ray Choudhury                   Yes               No
         Ritajyoti Bandyopadhyay                   Yes              Yes
            S. S. V. Rama Sastry                   Yes              Yes
              S. Arulananda babu                   Yes              Yes
              Sabyasachi Rakshit                   Yes               No
              Sadhan Chandra Das                   Yes              Yes
          Samarjit Bhattacharyya                   Yes              Yes
              Samir Kumar Biswas                   Yes              Yes
                    Samrat Ghosh                   Yes              Yes
             Samrat Mukhopadhyay                   Yes              Yes
                Sajal Kumar Giri                   Yes               No
                   Sanjay Mandal                    No               No
               Sanchita Sengupta                   Yes              Yes
                Sandeep K. Goyal                   Yes               No
                    Sanjay Singh                   Yes              Yes
                   Sanjeev Kumar                   Yes              Yes
               Santanu Kumar Pal                   Yes              Yes
           Santhosh Kumar Pamula                   Yes              Yes
              Santosh B. Satbhai                   Yes              Yes
                   Satyajit Jena                    No               No
                   Shane D'Mello                   Yes               No
           Sharmila Bhattacharya                   Yes              Yes
                Sharvan Sehrawat                   Yes              Yes
           Shashi Bhushan Pandit                   Yes               No
            Shravan Kumar Mishra                   Yes              Yes
                      Soma Maity                   Yes               No
            Sourabh Bhattacharya                   Yes              Yes
                Subhabrata Maiti                   Yes              Yes
                  Sudeshna Sinha                   Yes              Yes
                    Sudip Mandal                    No               No
           Sugumar Venkataramani                   Yes              Yes
              Suman Kumar Barman                   Yes               No
                  Sunil A. Patil                   Yes              Yes
                Tanusree Khandai                   Yes               No
                   Tripta Bhatia                   Yes              Yes
                 Ujjal K. Gautam                   Yes              Yes
                       V. Rajesh                   Yes              Yes
                   Vaibhav Vaish                   Yes              Yes
      Varadharaj Ravi Srinivasan                   Yes               No
                 Vidya Devi Negi                   Yes              Yes
                   Vinayak Sinha                   Yes              Yes
                 Vishal Bhardwaj                   Yes              Yes
               Yashonidhi Pandey                    No               No
                    Yogesh Singh                   Yes              Yes
              Yunus Ali Pulpadan                   Yes              Yes
                  Meenakshi Devi                    No               No
            Vinesh Shenoi Naresh                    No               No
           Dr. T V Venkateswaran                    No               No
Prof. Shashi Kant Raichand Dugad                    No               No
                Prof. Biman Nath                    No               No
                 Prof. Madan Rao                    No               No
            Prof. N.Sathyamurthy                   Yes               No
        Prof. Valakunja Nagaraja                    No               No
               Prof. Dhruv Raina                    No               No
        Prof. Kulinder Pal Singh                    No               No
      Prof. Sudesh Kaur Khanduja                   Yes              Yes
     Prof. Anand Kumar Bachhawat                   Yes               No
      Prof. Kapil Hari Paranjape                   Yes              Yes

Saving the csv data files

In [254]:
career_summary.to_csv("faculty_career_summary.csv", index=False)
print("Saved as faculty_career_summary.csv")

Saved as faculty_career_summary.csv

In [255]:

summary = career_summary.merge(
    research_summary[
        ["Name", "Publication Available", "Awards Available"]
    ],
    on="Name",
    how="left"
)

summary.to_csv("summary_of_faculty.csv", index=False)

print("Updated summary_of_faculty.csv")

Updated summary_of_faculty.csv

In [256]:
df = pd.read_csv("summary_of_faculty.csv")
df

,Name,PhD Year,PhD Institution,Postdoc,Assistant Professor,Associate Professor,Professor,Other positions,Publication Available,Awards Available
0,Abhik Ganguli,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,No
1,Abhishek Chaudhuri,NaN,NaN,NaN,"2012 - 2018: Assistant Professor, IISER Mohali","Since 2018: Associate Professor, IISER Mohali",NaN,NaN,Yes,No
2,Adrene Freeda Dcruz,2006 - 2011:,IIT Kanpur,NaN,"Since 2015: Assistant Professor, IISER Mohali",NaN,NaN,NaN,Yes,Yes
3,Alok Maharana,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,No
4,Ambresh Shivaji,2006 - 2012:,"Institute Bhubaneswar, India","2016 - 2018: Postdoctoral Fellow, CP3, Univers...",NaN,NaN,NaN,"2004 - 2006: M.Sc. in Physics, IIT Kanpur, Ind...",Yes,Yes
...,...,...,...,...,...,...,...,...,...,...
130,Prof. Dhruv Raina,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,No
131,Prof. Kulinder Pal Singh,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,No
132,Prof. Sudesh Kaur Khanduja,1973 - 1978:,"(Mathematics), Panjab University, Chandigarh",NaN,NaN,NaN,"Since 2017: Emeritus Professor, Department of ...","1978 - 1986: Lecturer , Dept. of Mathematics, ...",Yes,Yes
133,Prof. Anand Kumar Bachhawat,NaN,NaN,NaN,NaN,NaN,NaN,"1993 - 2010: Scientist, IMTECH CSIR",Yes,No
134,Prof. Kapil Hari Paranjape,1982 - 1992:,University of Mumbai (based on work done at TIFR),NaN,"1990 - 1991: Visiting Assistant Professor, Dep...","1996 - 2003: Associate Professor, IMSc","2003 - 2011: Professor, IMSc (on long leave fr...",2023 - 2025: Member (Convenor for 2023 - 2024)...,Yes,Yes

In [257]:
print(df.shape)
print(df.columns.tolist())

(135, 10)
['Name', 'PhD Year', 'PhD Institution', 'Postdoc', 'Assistant Professor', 'Associate Professor', 'Professor', 'Other positions', 'Publication Available', 'Awards Available']

In [258]:
df_clean.to_csv("iisermohali_faculty_clean.csv", index=False)

In [259]:

summary = pd.read_csv("summary_of_faculty.csv")

df_clean = df_clean.merge(
    summary,
    on="Name",
    how="left",
    suffixes=("", "_summary")
)
df_clean.to_csv("iisermohali_faculty_clean.csv", index=False)

In [260]:
k = pd.read_csv("iisermohali_faculty_clean.csv")
k

,Name,Department,Designation,Email,Profile Link,Category,Research Area,Research Interests,Career Highlights,Awards,Publications,PhD Year,PhD Institution,Postdoc,Assistant Professor,Associate Professor,Professor,Other positions,Publication Available,Awards Available
0,Abhik Ganguli,DMS,Assistant Professor,aganguli,https://www.iisermohali.ac.in/faculty/dms/agan...,Regular Faculty,Number Theory,"My research interests are in number theory, pa...","Ph.D., University of Chicago",NaN,Abhik Ganguli and Suneel Kumar. On the local c...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,No
1,Abhishek Chaudhuri,DPS,Professor,abhishek,https://www.iisermohali.ac.in/faculty/dps/abhi...,Regular Faculty,Condensed Matter Physics: Soft and Biological ...,The aim of our group is to understand the phys...,"Since 2018 : Associate Professor, IISER Mohali...",NaN,Chamkor Singh and Abhishek Chaudhuri. Anomalou...,NaN,NaN,NaN,"2012 - 2018: Assistant Professor, IISER Mohali","Since 2018: Associate Professor, IISER Mohali",NaN,NaN,Yes,No
2,Adrene Freeda Dcruz,HSS,Associate Professor,adrene,https://www.iisermohali.ac.in/faculty/hss/adrene,Regular Faculty,"Science-in-theatre, Media studies, Trauma stud...",I work in the field of Science-in-theatre whic...,"Since 2015 : Assistant Professor, IISER Mohali...",Best Teacher's Award,{bibtex}adrene.bib{/bibtex},2006 - 2011:,IIT Kanpur,NaN,"Since 2015: Assistant Professor, IISER Mohali",NaN,NaN,NaN,Yes,Yes
3,Alok Maharana,DMS,Assistant Professor,maharana,https://www.iisermohali.ac.in/faculty/dms/maha...,Regular Faculty,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,No
4,Ambresh Shivaji,DPS,Associate Professor,ashivaji,https://www.iisermohali.ac.in/faculty/dps/ashi...,Regular Faculty,Theoretical High Energy Physics,"Phenomenology of Standard Model and Beyond, Hi...","2016 - 2018 : Postdoctoral Fellow, CP3, Univer...","Member, National Steering Committee, Vigyan Pr...","Mandeep Kaur, Maguni Mahakhud, Ambresh Shivaji...",2006 - 2012:,"Institute Bhubaneswar, India","2016 - 2018: Postdoctoral Fellow, CP3, Univers...",NaN,NaN,NaN,"2004 - 2006: M.Sc. in Physics, IIT Kanpur, Ind...",Yes,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
130,Prof. Dhruv Raina,HSS,NaN,-,NaN,Honorary Professors,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,No
131,Prof. Kulinder Pal Singh,DPS,INSA Senior Scientist,kps,NaN,Honorary Professors,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,No
132,Prof. Sudesh Kaur Khanduja,DMS,INSA Honorary Scientist,skhanduja,https://www.iisermohali.ac.in/faculty/dms/skha...,Honorary Professors,Algebraic Number Theory and Valuation Theory,"I am mainly interested in valuations, speciall...","Since 2017 : Emeritus Professor, Department of...",• Srinivasa Ramanujan Medal of Indian National...,{bibtex}skhanduja.tex{/bibtex} Complete list o...,1973 - 1978:,"(Mathematics), Panjab University, Chandigarh",NaN,NaN,NaN,"Since 2017: Emeritus Professor, Department of ...","1978 - 1986: Lecturer , Dept. of Mathematics, ...",Yes,Yes
133,Prof. Anand Kumar Bachhawat,DBS,NaN,anand,https://www.iisermohali.ac.in/faculty/dbs/anand,Emeritus Professors,Microbial genetics and biochemistry,Areas of research and interest are: Understand...,"1993 - 2010 : Scientist, IMTECH CSIR",NaN,{bibtex}a.k.bachhawat.docx{/bibtex},NaN,NaN,NaN,NaN,NaN,NaN,"1993 - 2010: Scientist, IMTECH CSIR",Yes,No
134,Prof. Kapil Hari Paranjape,DMS,NaN,kapil,https://www.iisermohali.ac.in/faculty/dms/kapil,Emeritus Professors,"Algebraic Geometry, Algebraic Number Theory, A...",1. Construction of Algebraic Cycles as indicat...,2023 - 2025 : Member (Convenor for 2023 - 2024...,Fellowship of Indian Academy of Sciences Banga...,Kapil Paranjape and Dinakar Ramakrishnan. Modu...,1982 - 1992:,University of Mumbai (based on work done at TIFR),NaN,"1990 - 1991: Visiting Assistant Professor, Dep...","1996 - 2003: Associate Professor, IMSc","2003 - 2011: Professor, IMSc (on long leave fr...",2023 - 2025: Member (Convenor for 2023 - 2024)...,Yes,Yes

Turning into SQL database

In [261]:
import sqlite3

In [262]:
conn = sqlite3.connect("iisermohali_faculty.db")

In [263]:
df_raw = pd.read_csv("iisermohali_faculty_complete_raw.csv")

df_raw.to_sql("faculty_raw", conn, if_exists="replace", index=False)
df_clean.to_sql("faculty_clean", conn, if_exists="replace", index=False)

135

Checking the tables in the database

In [264]:
query = """
SELECT name
FROM sqlite_master
WHERE type='table';
"""

pd.read_sql(query, conn)

            name
0    faculty_raw
1  faculty_clean

In [265]:
query = """
SELECT
    (SELECT COUNT(*) FROM faculty_raw) AS raw_count,
    (SELECT COUNT(*) FROM faculty_clean) AS clean_count;
"""

pd.read_sql(query, conn)

   raw_count  clean_count
0        136          135

In [266]:
query = """
SELECT Department, COUNT(*) AS Count
FROM faculty_clean
GROUP BY Department
ORDER BY Count DESC;
"""

sql_department_counts = pd.read_sql(query, conn)

sql_department_counts

  Department  Count
0        DPS     32
1        DBS     31
2        DCS     26
3        DMS     23
4        EES     13
5        HSS     10

In [267]:
pandas_department_counts = (
    df_clean["Department"]
    .value_counts()
    .rename_axis("Department")
    .reset_index(name="Count")
)

pandas_department_counts

  Department  Count
0        DPS     32
1        DBS     31
2        DCS     26
3        DMS     23
4        EES     13
5        HSS     10