In [1]:
import pandas as pd

Cleaning the file

In [12]:
df= pd.read_csv(r"iisermohali_faculty_complete_raw_Copy.csv")
df.head()

,Name,Department,Designation,Email,Profile Link,Category,Research Area,Research Interests,Career Highlights,Awards,Publications
0,Abhik Ganguli,DMS,Assistant Professor,aganguli,https://www.iisermohali.ac.in/faculty/dms/agan...,NaN,Number Theory,"My research interests are in number theory, pa...","Ph.D., University of Chicago",NaN,Abhik Ganguli and Suneel Kumar. On the local c...
1,Abhishek Chaudhuri,DPS,Professor,abhishek,https://www.iisermohali.ac.in/faculty/dps/abhi...,NaN,Condensed Matter Physics: Soft and Biological ...,The aim of our group is to understand the phys...,"Since 2018 : Associate Professor, IISER Mohali...",NaN,Chamkor Singh and Abhishek Chaudhuri. Anomalou...
2,Adrene Freeda Dcruz,HSS,Associate Professor,adrene,https://www.iisermohali.ac.in/faculty/hss/adrene,NaN,"Science-in-theatre, Media studies, Trauma stud...",I work in the field of Science-in-theatre whic...,"Since 2015 : Assistant Professor, IISER Mohali...",Best Teacher's Award,{bibtex}adrene.bib{/bibtex}
3,Alok Maharana,DMS,Assistant Professor,maharana,https://www.iisermohali.ac.in/faculty/dms/maha...,NaN,NaN,NaN,NaN,NaN,NaN
4,Ambresh Shivaji,DPS,Associate Professor,ashivaji,https://www.iisermohali.ac.in/faculty/dps/ashi...,NaN,Theoretical High Energy Physics,"Phenomenology of Standard Model and Beyond, Hi...","2016 - 2018 : Postdoctoral Fellow, CP3, Univer...","Member, National Steering Committee, Vigyan Pr...","Mandeep Kaur, Maguni Mahakhud, Ambresh Shivaji..."

cleaning

In [34]:
df_clean = pd.read_csv("iisermohali_faculty_complete_raw_Copy.csv")

print("Rows:", len(df_clean))
print(df_clean["Category"].value_counts())

Rows: 136
Category
Former Faculty          2
Honorary Professors     2
Regular Faculty         1
Inspire Faculty         1
Lecturers               1
Visiting Faculty        1
Adjunct Faculty         1
Emeritus Professors     1
Administrative Staff    1
Technical Staff         1
Institute Fellows       1
Project Scientists      1
Name: count, dtype: int64

In [56]:
df_clean = pd.read_csv("iisermohali_faculty_complete_raw_Copy.csv")
df
df["Department"].value_counts()
df["Designation"].value_counts()

Designation
Assistant Professor        46
Associate Professor        40
Professor                  39
INSA Honorary Scientist     1
Attendant                   1
Jr. Technical Assistant     1
Name: count, dtype: int64

In [57]:
df_clean = df_clean[df_clean["Designation"] != "Jr. Technical Assistant"].copy()
df_clean = df_clean[df_clean["Designation"] != "Attendant"].copy()
df_clean = df_clean[df_clean["Department"] != "Assistant Professor"].copy()
df_clean = df_clean[df_clean["Department"] != "Physics"].copy()
df_clean

,Name,Department,Designation,Email,Profile Link,Category,Research Area,Research Interests,Career Highlights,Awards,Publications
0,Abhik Ganguli,DMS,Assistant Professor,aganguli,https://www.iisermohali.ac.in/faculty/dms/agan...,NaN,Number Theory,"My research interests are in number theory, pa...","Ph.D., University of Chicago",NaN,Abhik Ganguli and Suneel Kumar. On the local c...
1,Abhishek Chaudhuri,DPS,Professor,abhishek,https://www.iisermohali.ac.in/faculty/dps/abhi...,NaN,Condensed Matter Physics: Soft and Biological ...,The aim of our group is to understand the phys...,"Since 2018 : Associate Professor, IISER Mohali...",NaN,Chamkor Singh and Abhishek Chaudhuri. Anomalou...
2,Adrene Freeda Dcruz,HSS,Associate Professor,adrene,https://www.iisermohali.ac.in/faculty/hss/adrene,NaN,"Science-in-theatre, Media studies, Trauma stud...",I work in the field of Science-in-theatre whic...,"Since 2015 : Assistant Professor, IISER Mohali...",Best Teacher's Award,{bibtex}adrene.bib{/bibtex}
3,Alok Maharana,DMS,Assistant Professor,maharana,https://www.iisermohali.ac.in/faculty/dms/maha...,NaN,NaN,NaN,NaN,NaN,NaN
4,Ambresh Shivaji,DPS,Associate Professor,ashivaji,https://www.iisermohali.ac.in/faculty/dps/ashi...,NaN,Theoretical High Energy Physics,"Phenomenology of Standard Model and Beyond, Hi...","2016 - 2018 : Postdoctoral Fellow, CP3, Univer...","Member, National Steering Committee, Vigyan Pr...","Mandeep Kaur, Maguni Mahakhud, Ambresh Shivaji..."
...,...,...,...,...,...,...,...,...,...,...,...
128,Prof. IBS Passi,DMS,Professor,NaN,NaN,Former Faculty,NaN,NaN,NaN,NaN,NaN
129,Prof. Dhruv Raina,HSS,NaN,-,NaN,Honorary Professors,NaN,NaN,NaN,NaN,NaN
130,Prof. Sudesh Kaur Khanduja,DMS,INSA Honorary Scientist,skhanduja,https://www.iisermohali.ac.in/faculty/dms/skha...,Honorary Professors,Algebraic Number Theory and Valuation Theory,"I am mainly interested in valuations, speciall...","Since 2017 : Emeritus Professor, Department of...",• Srinivasa Ramanujan Medal of Indian National...,{bibtex}skhanduja.tex{/bibtex} Complete list o...
131,Prof. Kapil Hari Paranjape,DMS,NaN,kapil,https://www.iisermohali.ac.in/faculty/dms/kapil,Emeritus Professors,"Algebraic Geometry, Algebraic Number Theory, A...",1. Construction of Algebraic Cycles as indicat...,2023 - 2025 : Member (Convenor for 2023 - 2024...,Fellowship of Indian Academy of Sciences Banga...,Kapil Paranjape and Dinakar Ramakrishnan. Modu...
135,Sohan Ghosh,DMS,NaN,NaN,NaN,Project Scientists,NaN,NaN,NaN,NaN,NaN

In [60]:
df_clean["Department"].value_counts()

Department
DPS    30
DBS    30
DMS    25
DCS    25
EES    13
HSS     9
Name: count, dtype: int64

In [62]:
df_clean.to_csv("iisermohali_faculty_clean.csv", index=False)
print("Saved!")
print("Rows:", len(df_clean))
print("Columns:", len(df_clean.columns))

Saved!
Rows: 132
Columns: 11

Turning into SQL

In [63]:
import sqlite3

In [64]:
conn = sqlite3.connect("iisermohali_faculty.db")

In [65]:
df_raw = pd.read_csv("iisermohali_faculty_complete_raw.csv")

df_raw.to_sql("faculty_raw", conn, if_exists="replace", index=False)
df_clean.to_sql("faculty_clean", conn, if_exists="replace", index=False)

132

In [66]:
query = """
SELECT name
FROM sqlite_master
WHERE type='table';
"""

pd.read_sql(query, conn)

            name
0    faculty_raw
1  faculty_clean

In [67]:
query = """
SELECT
    (SELECT COUNT(*) FROM faculty_raw) AS raw_count,
    (SELECT COUNT(*) FROM faculty_clean) AS clean_count;
"""

pd.read_sql(query, conn)

   raw_count  clean_count
0        136          132

In [68]:
query = """
SELECT Department, COUNT(*) AS Count
FROM faculty_clean
GROUP BY Department
ORDER BY Count DESC;
"""

sql_department_counts = pd.read_sql(query, conn)

sql_department_counts

  Department  Count
0        DPS     30
1        DBS     30
2        DMS     25
3        DCS     25
4        EES     13
5        HSS      9

In [69]:
pandas_department_counts = (
    df_clean["Department"]
    .value_counts()
    .rename_axis("Department")
    .reset_index(name="Count")
)

pandas_department_counts

  Department  Count
0        DPS     30
1        DBS     30
2        DMS     25
3        DCS     25
4        EES     13
5        HSS      9