Exploraratory Data Analysis

Importing relevant Libraries

In [200]:
import pandas as pd
import matplotlib.pyplot as plt

Lets explore the data

In [201]:
#First few records of the dataset
df= pd.read_csv("iisermohali_faculty_clean_Copy.csv")
df.head()

,Name,Department,Designation,Email,Profile Link,Category,Research Area,Research Interests,Career Highlights,Awards,Publications,PhD Year,PhD Institution,Postdoc,Assistant Professor,Associate Professor,Professor,Other positions,Publication Available,Awards Available
0,Abhik Ganguli,DMS,Assistant Professor,aganguli,https://www.iisermohali.ac.in/faculty/dms/agan...,Regular Faculty,Number Theory,"My research interests are in number theory, pa...","Ph.D., University of Chicago",NaN,Abhik Ganguli and Suneel Kumar. On the local c...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,No
1,Abhishek Chaudhuri,DPS,Professor,abhishek,https://www.iisermohali.ac.in/faculty/dps/abhi...,Regular Faculty,Condensed Matter Physics: Soft and Biological ...,The aim of our group is to understand the phys...,"Since 2018 : Associate Professor, IISER Mohali...",NaN,Chamkor Singh and Abhishek Chaudhuri. Anomalou...,NaN,NaN,NaN,"2012 - 2018: Assistant Professor, IISER Mohali","Since 2018: Associate Professor, IISER Mohali",NaN,NaN,Yes,No
2,Adrene Freeda Dcruz,HSS,Associate Professor,adrene,https://www.iisermohali.ac.in/faculty/hss/adrene,Regular Faculty,"Science-in-theatre, Media studies, Trauma stud...",I work in the field of Science-in-theatre whic...,"Since 2015 : Assistant Professor, IISER Mohali...",Best Teacher's Award,{bibtex}adrene.bib{/bibtex},2006 - 2011:,IIT Kanpur,NaN,"Since 2015: Assistant Professor, IISER Mohali",NaN,NaN,NaN,Yes,Yes
3,Alok Maharana,DMS,Assistant Professor,maharana,https://www.iisermohali.ac.in/faculty/dms/maha...,Regular Faculty,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,No
4,Ambresh Shivaji,DPS,Associate Professor,ashivaji,https://www.iisermohali.ac.in/faculty/dps/ashi...,Regular Faculty,Theoretical High Energy Physics,"Phenomenology of Standard Model and Beyond, Hi...","2016 - 2018 : Postdoctoral Fellow, CP3, Univer...","Member, National Steering Committee, Vigyan Pr...","Mandeep Kaur, Maguni Mahakhud, Ambresh Shivaji...",2006 - 2012:,"Institute Bhubaneswar, India","2016 - 2018: Postdoctoral Fellow, CP3, Univers...",NaN,NaN,NaN,"2004 - 2006: M.Sc. in Physics, IIT Kanpur, Ind...",Yes,Yes


Dataset overview

In [202]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 131 entries, 0 to 130
Data columns (total 20 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Name                   131 non-null    str
 1   Department             131 non-null    str
 2   Designation            125 non-null    str
 3   Email                  128 non-null    str
 4   Profile Link           124 non-null    str
 5   Category               131 non-null    str
 6   Research Area          111 non-null    str
 7   Research Interests     112 non-null    str
 8   Career Highlights      109 non-null    str
 9   Awards                 81 non-null     str
 10  Publications           111 non-null    str
 11  PhD Year               98 non-null     str
 12  PhD Institution        98 non-null     str
 13  Postdoc                58 non-null     str
 14  Assistant Professor    61 non-null     str
 15  Associate Professor    24 non-null     str
 16  Professor              19 non-null     str
 17  Other positions        102 non-null    str
 18  Publication Available  131 non-null    str
 19  Awards Available       131 non-null    str
dtypes: str(20)
memory usage: 20.6 KB

In [203]:
print("Number of rows:" + str(df.shape[0]))
print("Number of columns:" + str(df.shape[1]))
print("Column names:" + str(df.columns.tolist()))
print("Data types:" + str(df.dtypes.tolist()))

Number of rows:131
Number of columns:20
Column names:['Name', 'Department', 'Designation', 'Email', 'Profile Link', 'Category', 'Research Area', 'Research Interests', 'Career Highlights', 'Awards', 'Publications', 'PhD Year', 'PhD Institution', 'Postdoc', 'Assistant Professor', 'Associate Professor', 'Professor', 'Other positions', 'Publication Available', 'Awards Available']
Data types:[<StringDtype(storage='python', na_value=nan)>, <StringDtype(storage='python', na_value=nan)>, <StringDtype(storage='python', na_value=nan)>, <StringDtype(storage='python', na_value=nan)>, <StringDtype(storage='python', na_value=nan)>, <StringDtype(storage='python', na_value=nan)>, <StringDtype(storage='python', na_value=nan)>, <StringDtype(storage='python', na_value=nan)>, <StringDtype(storage='python', na_value=nan)>, <StringDtype(storage='python', na_value=nan)>, <StringDtype(storage='python', na_value=nan)>, <StringDtype(storage='python', na_value=nan)>, <StringDtype(storage='python', na_value=nan)>, <StringDtype(storage='python', na_value=nan)>, <StringDtype(storage='python', na_value=nan)>, <StringDtype(storage='python', na_value=nan)>, <StringDtype(storage='python', na_value=nan)>, <StringDtype(storage='python', na_value=nan)>, <StringDtype(storage='python', na_value=nan)>, <StringDtype(storage='python', na_value=nan)>]

In [204]:
df.describe()

,Name,Department,Designation,Email,Profile Link,Category,Research Area,Research Interests,Career Highlights,Awards,Publications,PhD Year,PhD Institution,Postdoc,Assistant Professor,Associate Professor,Professor,Other positions,Publication Available,Awards Available
count,131,131,125,128,124,131,111,112,109,81,111,98,98,58,61,24,19,102,131,131
unique,131,6,4,127,124,8,111,112,109,81,111,64,93,58,57,20,18,102,2,2
top,Abhik Ganguli,DPS,Assistant Professor,-,https://www.iisermohali.ac.in/faculty/dms/agan...,Regular Faculty,Number Theory,"My research interests are in number theory, pa...","Ph.D., University of Chicago",Best Teacher's Award,Abhik Ganguli and Suneel Kumar. On the local c...,1999 - 2005:,IIT Kanpur,"2016 - 2018: Postdoctoral Fellow, CP3, Univers...","2017 - 2023: Assistant Professor, IISER Mohali","Since 2020: Associate Professor, IISER Mohali","Since 2020: Professor, IISER Mohali","2004 - 2006: M.Sc. in Physics, IIT Kanpur, Ind...",Yes,Yes
freq,1,30,45,2,1,122,1,1,1,1,1,4,2,1,3,2,2,1,111,81

Data Quality

Missing values

In [205]:
missing = df.isnull().sum()
print(missing)

Name                       0
Department                 0
Designation                6
Email                      3
Profile Link               7
Category                   0
Research Area             20
Research Interests        19
Career Highlights         22
Awards                    50
Publications              20
PhD Year                  33
PhD Institution           33
Postdoc                   73
Assistant Professor       70
Associate Professor      107
Professor                112
Other positions           29
Publication Available      0
Awards Available           0
dtype: int64

In [206]:
missingpercentage = df.isnull().sum() / len(df)* 100
print(missingpercentage)

Name                      0.000000
Department                0.000000
Designation               4.580153
Email                     2.290076
Profile Link              5.343511
Category                  0.000000
Research Area            15.267176
Research Interests       14.503817
Career Highlights        16.793893
Awards                   38.167939
Publications             15.267176
PhD Year                 25.190840
PhD Institution          25.190840
Postdoc                  55.725191
Assistant Professor      53.435115
Associate Professor      81.679389
Professor                85.496183
Other positions          22.137405
Publication Available     0.000000
Awards Available          0.000000
dtype: float64

In [207]:
missing_table = pd.DataFrame({
    "Missing Count": df.isnull().sum(),
    "Missing Percentage": (df.isnull().sum() / len(df)) * 100
})

missing_table

                       Missing Count  Missing Percentage
Name                               0            0.000000
Department                         0            0.000000
Designation                        6            4.580153
Email                              3            2.290076
Profile Link                       7            5.343511
Category                           0            0.000000
Research Area                     20           15.267176
Research Interests                19           14.503817
Career Highlights                 22           16.793893
Awards                            50           38.167939
Publications                      20           15.267176
PhD Year                          33           25.190840
PhD Institution                   33           25.190840
Postdoc                           73           55.725191
Assistant Professor               70           53.435115
Associate Professor              107           81.679389
Professor                        112           85.496183
Other positions                   29           22.137405
Publication Available              0            0.000000
Awards Available                   0            0.000000

import matplotlib.pyplot as plt

missing = df.isna().sum()

plt.bar(missing.index, missing.values)
plt.xticks(rotation=45, ha="right")
plt.ylabel("Number of Missing Values")
plt.title("Missing Values by Column")
plt.tight_layout()
plt.show()

Duplicates

In [208]:
print("Number of duplicate rows:", df.duplicated().sum())

Number of duplicate rows: 0

Empty Values

In [209]:
empty_values = (df == "").sum()

print(empty_values)

Name                     0
Department               0
Designation              0
Email                    0
Profile Link             0
Category                 0
Research Area            0
Research Interests       0
Career Highlights        0
Awards                   0
Publications             0
PhD Year                 0
PhD Institution          0
Postdoc                  0
Assistant Professor      0
Associate Professor      0
Professor                0
Other positions          0
Publication Available    0
Awards Available         0
dtype: int64

Unique values

In [210]:
for col in df.columns:
    print("\n" + "=" * 60)
    print(col)
    print("Unique:", df[col].nunique())
    print(df[col].value_counts(dropna=False))

============================================================
Name
Unique: 131
Name
Abhik Ganguli                 1
Abhishek Chaudhuri            1
Adrene Freeda Dcruz           1
Alok Maharana                 1
Ambresh Shivaji               1
                             ..
Prof. IBS Passi               1
Prof. Dhruv Raina             1
Prof. Sudesh Kaur Khanduja    1
Prof. Kapil Hari Paranjape    1
Sohan Ghosh                   1
Name: count, Length: 131, dtype: int64

============================================================
Department
Unique: 6
Department
DPS    30
DBS    30
DMS    25
DCS    25
EES    12
HSS     9
Name: count, dtype: int64

============================================================
Designation
Unique: 4
Designation
Assistant Professor        45
Associate Professor        40
Professor                  39
NaN                         6
INSA Honorary Scientist     1
Name: count, dtype: int64

============================================================
Email
Unique: 127
Email
NaN                            3
-                              2
aganguli                       1
abhishek                       1
adrene                         1
                              ..
yunusp                         1
vineshshenoi                   1
bimannath@iisermohali.ac.in    1
skhanduja                      1
kapil                          1
Name: count, Length: 128, dtype: int64

============================================================
Profile Link
Unique: 124
Profile Link
NaN                                                    7
https://www.iisermohali.ac.in/faculty/dms/aganguli     1
https://www.iisermohali.ac.in/faculty/dps/abhishek     1
https://www.iisermohali.ac.in/faculty/hss/adrene       1
https://www.iisermohali.ac.in/faculty/dms/maharana     1
                                                      ..
https://www.iisermohali.ac.in/faculty/dms/ypandey      1
https://www.iisermohali.ac.in/faculty/dps/yogesh       1
https://www.iisermohali.ac.in/faculty/ees/yunusp       1
https://www.iisermohali.ac.in/faculty/dms/skhanduja    1
https://www.iisermohali.ac.in/faculty/dms/kapil        1
Name: count, Length: 125, dtype: int64

============================================================
Category
Unique: 8
Category
Regular Faculty        122
Former Faculty           2
Honorary Professors      2
Lecturers                1
Visiting Faculty         1
Adjunct Faculty          1
Emeritus Professors      1
Project Scientists       1
Name: count, dtype: int64

============================================================
Research Area
Unique: 111
Research Area
NaN                                                                            20
Number Theory                                                                   1
Condensed Matter Physics: Soft and Biological Matter                            1
Science-in-theatre, Media studies, Trauma studies, Scatology                    1
Theoretical High Energy Physics                                                 1
                                                                               ..
Experimental High Energy Physics                                                1
Experimental Condensed Matter Physics, Quantum Materials                        1
Natural Hazards, Geomorphology, Remote Sensing and GIS, Disaster Mitigation     1
Algebraic Number Theory and Valuation Theory                                    1
Algebraic Geometry, Algebraic Number Theory, Algebraic Topology                 1
Name: count, Length: 112, dtype: int64

============================================================
Research Interests
Unique: 112
Research Interests

Counts

In [211]:
department_counts = df["Department"].value_counts()

department_counts

Department
DPS    30
DBS    30
DMS    25
DCS    25
EES    12
HSS     9
Name: count, dtype: int64

plt.figure(figsize=(10, 6))

department_counts.plot(kind="bar")

plt.title("Number of Faculty by Department")
plt.xlabel("Department")
plt.ylabel("Number of Faculty")
plt.xticks(rotation=45, ha="right")
plt.tight_layout()
plt.show()

In [212]:
designation_counts = df["Designation"].value_counts()

designation_counts

Designation
Assistant Professor        45
Associate Professor        40
Professor                  39
INSA Honorary Scientist     1
Name: count, dtype: int64

plt.figure(figsize=(10, 6))

designation_counts.plot(kind="bar")

plt.title("Number of Faculty by Designation")
plt.xlabel("Designation")
plt.ylabel("Number of Faculty")
plt.xticks(rotation=45, ha="right")
plt.tight_layout()
plt.show()

In [213]:
department_designation = pd.crosstab(
    df["Department"],
    df["Designation"]
)

department_designation

Designation,Assistant Professor,Associate Professor,INSA Honorary Scientist,Professor
Department,,,,
DBS,7,10,0,12
DCS,8,10,0,7
DMS,12,5,1,5
DPS,8,8,0,12
EES,7,3,0,2
HSS,3,4,0,1

department_designation.plot(
    kind="bar",
    stacked=True,
    figsize=(12, 6)
)

plt.title("Faculty Designation by Department")
plt.xlabel("Department")
plt.ylabel("Number of Faculty")
plt.xticks(rotation=45, ha="right")
plt.tight_layout()
plt.show()

Email information

In [214]:
email_available = df["Email"].notna().value_counts()

email_available

Email
True     128
False      3
Name: count, dtype: int64

In [215]:
email_available = df["Email"].notna().value_counts()

email_available

Email
True     128
False      3
Name: count, dtype: int64

df["Email"].notna().map({
    True: "Available",
    False: "Missing"
}).value_counts().plot(kind="bar")

plt.title("Email Availability")
plt.xlabel("Email Status")
plt.ylabel("Number of Faculty")
plt.xticks(rotation=0)
plt.show()

Profile Link

In [216]:
profile_available = df["Profile Link"].notna()

print("Profiles with URL:", profile_available.sum())
print("Profiles without URL:", (~profile_available).sum())

Profiles with URL: 124
Profiles without URL: 7

In [217]:
print(
    f"{profile_available.mean() * 100:.2f}% "
    "of records have a profile URL."
)

94.66% of records have a profile URL.

In [218]:
valid_urls = df["Profile Link"].astype(str).str.startswith("http")

print("URLs beginning with http:", valid_urls.sum())

URLs beginning with http: 124

Research Area

In [219]:
df["Research Area"]

0                                          Number Theory
1      Condensed Matter Physics: Soft and Biological ...
2      Science-in-theatre, Media studies, Trauma stud...
3                                                    NaN
4                        Theoretical High Energy Physics
                             ...
126                                                  NaN
127                                                  NaN
128         Algebraic Number Theory and Valuation Theory
129    Algebraic Geometry, Algebraic Number Theory, A...
130                                                  NaN
Name: Research Area, Length: 131, dtype: str

In [220]:
print(
    "Missing research areas:",
    df["Research Area"].isnull().sum()
)

Missing research areas: 20

In [221]:
df["Research Area"].value_counts()

Research Area
Number Theory                                                                  1
Condensed Matter Physics: Soft and Biological Matter                           1
Science-in-theatre, Media studies, Trauma studies, Scatology                   1
Theoretical High Energy Physics                                                1
Molecular and Structural Biology                                               1
                                                                              ..
Experimental High Energy Physics                                               1
Experimental Condensed Matter Physics, Quantum Materials                       1
Natural Hazards, Geomorphology, Remote Sensing and GIS, Disaster Mitigation    1
Algebraic Number Theory and Valuation Theory                                   1
Algebraic Geometry, Algebraic Number Theory, Algebraic Topology                1
Name: count, Length: 111, dtype: int64

df["Research Area"].value_counts().plot(
    kind="bar",
    figsize=(12, 6)
)

plt.title("Faculty by Research Area")
plt.xlabel("Research Area")
plt.ylabel("Number of Faculty")
plt.xticks(rotation=45, ha="right")
plt.tight_layout()
plt.show()

Finding Research Area keywords

In [222]:
research = (
    df["Research Area"]
    .dropna()
    .str.split(",")
    .explode()
    .str.strip()
)

In [223]:
research_counts = research.value_counts()

research_counts.head(20)

Research Area
Algebraic Geometry                                          4
catalysis                                                   2
Evolutionary Biology                                        2
Number Theory                                               1
Condensed Matter Physics: Soft and Biological Matter        1
Science-in-theatre                                          1
Media studies                                               1
Trauma studies                                              1
Scatology                                                   1
Theoretical High Energy Physics                             1
Molecular and Structural Biology                            1
Algebra : central simple algebras and related structures    1
word maps on groups                                         1
Crystallography                                             1
solid state chemistry                                       1
crystal engineering                                         1
polymorphism                                                1
Computational Soft and Biological Matter Physics            1
Geochemistry                                                1
Labour geography                                            1
Name: count, dtype: int64

research_counts.head(15).plot(
    kind="bar",
    figsize=(12, 6)
)

plt.title("Most Common Research Areas")
plt.xlabel("Research Area")
plt.ylabel("Number of Faculty")
plt.xticks(rotation=45, ha="right")
plt.tight_layout()
plt.show()

Category distribution

In [224]:
df["Category"].value_counts()

Category
Regular Faculty        122
Former Faculty           2
Honorary Professors      2
Lecturers                1
Visiting Faculty         1
Adjunct Faculty          1
Emeritus Professors      1
Project Scientists       1
Name: count, dtype: int64

df["Category"].value_counts().plot(kind="bar")
plt.title("Faculty by Category")
plt.xlabel("Category")
plt.ylabel("Number of Faculty")
plt.xticks(rotation=0)
plt.show()

PhD year distribution

In [225]:
print(df["PhD Year"].dtype)
df["PhD Year"].value_counts().sort_index()

str

PhD Year
1973 - 1978:    1
1980 - 1984:    1
1982 - 1992:    1
1985 - 1991:    1
1991 - 1997:    1
               ..
2012 - 2018:    1
2012:           1
2014 - 2019:    1
2015 - 2020:    1
2024 - 2018:    1
Name: count, Length: 64, dtype: int64

df["PhD Year"].dropna().plot(
    kind="hist",
    bins=15
)

plt.title("Distribution of PhD Years")
plt.xlabel("PhD Year")
plt.ylabel("Number of Faculty")
plt.show()

Faculty by PhD institution

In [226]:
df["PhD Institution"].value_counts().head(15)

PhD Institution
IIT Kanpur                                                                                                                                                                 2
Tata Institute of Fundamental Research, Mumbai                                                                                                                             2
Indian Institute of Technology Kanpur                                                                                                                                      2
Indian Institute  (IISc), Bangalore                                                                                                                                        2
TIFR Mumbai                                                                                                                                                                2
Institute  Bhubaneswar, India                                                                                                                                              1
(Structural Biology), CSIR-Institute of Microbial Technology, Chandigarh, India                                                                                            1
Indian Institute , Bangalore, India                                                                                                                                        1
in Biophysics, Université Toulouse III - Paul Sabatier, Toulouse, France                                                                                                   1
Department of Botany, Banaras Hindu University, Varanasi                                                                                                                   1
(Dual Title in Geography and Women's Studies), Pennsylvania State University, University Park, PA MS (Architecture), Pennsylvania State University, University Park, PA    1
The Institute of Mathematical Sciences (under Homi Bhabha National Institute)                                                                                              1
National Institute of Cholera and Enteric Diseases, Kolkata, West Bengal ( awarded by Jadavpur University in 2005) MSc (Botany) from University of Burdwan, West Bengal    1
Indian Institute , Bangalore                                                                                                                                               1
in Civil Engineering, IIT Guwahati                                                                                                                                         1
Name: count, dtype: int64

df["PhD Institution"].value_counts().head(15).plot(
    kind="bar",
    figsize=(12,6)
)

plt.title("Top PhD Institutions of Faculty")
plt.xlabel("PhD Institution")
plt.ylabel("Number of Faculty")
plt.xticks(rotation=45, ha="right")
plt.tight_layout()
plt.show()

Publications and awards availability

In [227]:
print(df["Publication Available"].value_counts())
print(df["Awards Available"].value_counts())

Publication Available
Yes    111
No      20
Name: count, dtype: int64
Awards Available
Yes    81
No     50
Name: count, dtype: int64

In [228]:
pd.crosstab(
    df["Publication Available"],
    df["Awards Available"]
)

Awards Available       No  Yes
Publication Available
No                     20    0
Yes                    30   81

Department × Category

In [229]:
pd.crosstab(
    df["Department"],
    df["Category"]
)

Category,Adjunct Faculty,Emeritus Professors,Former Faculty,Honorary Professors,Lecturers,Project Scientists,Regular Faculty,Visiting Faculty
Department,,,,,,,,
DBS,0,0,1,0,1,0,28,0
DCS,0,0,0,0,0,0,25,0
DMS,0,1,1,1,0,1,21,0
DPS,1,0,0,0,0,0,28,1
EES,0,0,0,0,0,0,12,0
HSS,0,0,0,1,0,0,8,0

pd.crosstab(
    df["Department"],
    df["Category"]
).plot(
    kind="bar",
    stacked=True,
    figsize=(12,6)
)

plt.title("Faculty Category by Department")
plt.xlabel("Department")
plt.ylabel("Number of Faculty")
plt.xticks(rotation=45, ha="right")
plt.tight_layout()
plt.show()

Department × publication availability

In [230]:
pd.crosstab(
    df["Department"],
    df["Publication Available"]
)

Publication Available  No  Yes
Department
DBS                     6   24
DCS                     1   24
DMS                     5   20
DPS                     7   23
EES                     0   12
HSS                     1    8

Department × awards availability

In [231]:
pd.crosstab(
    df["Department"],
    df["Awards Available"]
)

Awards Available  No  Yes
Department
DBS                9   21
DCS                7   18
DMS               18    7
DPS               12   18
EES                0   12
HSS                4    5

PhD year × department

In [232]:
df["PhD Start Year"] = (
    df["PhD Year"]
    .astype(str)
    .str.extract(r"(\d{4})")[0]
    .astype(float)
)

df["PhD Decade"] = (
    (df["PhD Start Year"] // 10 * 10)
    .astype("Int64")
    .astype(str)
    + "s"
)

phd_department = pd.crosstab(
    df["Department"],
    df["PhD Decade"]
)

print(phd_department)

PhD Decade  1970s  1980s  1990s  2000s  2010s  2020s
Department
DBS             0      1      6     12      3      0
DCS             0      0      7     13      3      0
DMS             1      1      2      9      2      1
DPS             0      1      6      9      4      0
EES             0      0      0      4      5      0
HSS             0      0      1      6      1      0

Postdoc experience by department

In [233]:
pd.crosstab(
    df["Department"],
    df["Postdoc"].notna()
)

Postdoc     False  True
Department
DBS             7     23
DCS            12     13
DMS            20      5
DPS            21      9
EES             6      6
HSS             7      2

Previous Career Experience

In [234]:
df["Previous Career Experience"] = (
    df[[
        "Postdoc",
        "Assistant Professor",
        "Associate Professor",
        "Professor",
        "Other positions"
    ]]
    .fillna("")
    .astype(str)
    .apply(
        lambda row: "Yes" if any(x.strip() for x in row) else "No",
        axis=1
    )
)

Experience = pd.crosstab(
    df["Department"],
    df["Previous Career Experience"]
)
print(Experience)

Previous Career Experience  No  Yes
Department
DBS                          6   24
DCS                          1   24
DMS                          9   16
DPS                          7   23
EES                          0   12
HSS                          1    8

Profile Completeness Score

In [235]:
cols = [
    "Email",
    "Profile Link",
    "Research Area",
    "Research Interests",
    "Career Highlights",
    "Awards",
    "Publications",
    "PhD Institution"
]

df["Profile Completeness"] = df[cols].notna().sum(axis=1)

print(df["Profile Completeness"].describe())

count    131.000000
mean       6.671756
std        2.264926
min        0.000000
25%        7.000000
50%        8.000000
75%        8.000000
max        8.000000
Name: Profile Completeness, dtype: float64

In [236]:
print(
    df.groupby("Department")["Profile Completeness"]
      .mean()
      .sort_values(ascending=False)
)

Department
EES    7.750000
DCS    7.480000
HSS    6.888889
DBS    6.500000
DPS    6.266667
DMS    5.960000
Name: Profile Completeness, dtype: float64

Text-length analysis

In [237]:
df["Research Interests Length"] = df["Research Interests"].fillna("").str.len()
df["Career Highlights Length"] = df["Career Highlights"].fillna("").str.len()
df["Publications Length"] = df["Publications"].fillna("").str.len()
df[
    ["Research Interests Length",
     "Career Highlights Length",
     "Publications Length"]
].describe()

,Research Interests Length,Career Highlights Length,Publications Length
count,131.00000,131.000000,131.000000
mean,60229.78626,477.496183,2987.549618
std,91732.27444,420.370869,5702.213036
min,0.00000,0.000000,0.000000
25%,21914.50000,219.500000,667.500000
50%,44724.00000,415.000000,1762.000000
75%,63423.50000,649.500000,2661.500000
max,785206.00000,2167.000000,51399.000000

In [238]:
df.to_csv("faculty_eda_done.csv", index=False)
df

,Name,Department,Designation,Email,Profile Link,Category,Research Area,Research Interests,Career Highlights,Awards,...,Other positions,Publication Available,Awards Available,PhD Start Year,PhD Decade,Previous Career Experience,Profile Completeness,Research Interests Length,Career Highlights Length,Publications Length
0,Abhik Ganguli,DMS,Assistant Professor,aganguli,https://www.iisermohali.ac.in/faculty/dms/agan...,Regular Faculty,Number Theory,"My research interests are in number theory, pa...","Ph.D., University of Chicago",NaN,...,NaN,Yes,No,NaN,NaN,No,6,13290,28,465
1,Abhishek Chaudhuri,DPS,Professor,abhishek,https://www.iisermohali.ac.in/faculty/dps/abhi...,Regular Faculty,Condensed Matter Physics: Soft and Biological ...,The aim of our group is to understand the phys...,"Since 2018 : Associate Professor, IISER Mohali...",NaN,...,NaN,Yes,No,NaN,NaN,Yes,6,116670,94,7258
2,Adrene Freeda Dcruz,HSS,Associate Professor,adrene,https://www.iisermohali.ac.in/faculty/hss/adrene,Regular Faculty,"Science-in-theatre, Media studies, Trauma stud...",I work in the field of Science-in-theatre whic...,"Since 2015 : Assistant Professor, IISER Mohali...",Best Teacher's Award,...,NaN,Yes,Yes,2006.0,2000s,Yes,8,7284,76,27
3,Alok Maharana,DMS,Assistant Professor,maharana,https://www.iisermohali.ac.in/faculty/dms/maha...,Regular Faculty,NaN,NaN,NaN,NaN,...,NaN,No,No,NaN,NaN,No,2,0,0,0
4,Ambresh Shivaji,DPS,Associate Professor,ashivaji,https://www.iisermohali.ac.in/faculty/dps/ashi...,Regular Faculty,Theoretical High Energy Physics,"Phenomenology of Standard Model and Beyond, Hi...","2016 - 2018 : Postdoctoral Fellow, CP3, Univer...","Member, National Steering Committee, Vigyan Pr...",...,"2004 - 2006: M.Sc. in Physics, IIT Kanpur, Ind...",Yes,Yes,2006.0,2000s,Yes,8,44724,414,1914
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
126,Prof. IBS Passi,DMS,Professor,NaN,NaN,Former Faculty,NaN,NaN,NaN,NaN,...,NaN,No,No,NaN,NaN,No,0,0,0,0
127,Prof. Dhruv Raina,HSS,NaN,-,NaN,Honorary Professors,NaN,NaN,NaN,NaN,...,NaN,No,No,NaN,NaN,No,1,0,0,0
128,Prof. Sudesh Kaur Khanduja,DMS,INSA Honorary Scientist,skhanduja,https://www.iisermohali.ac.in/faculty/dms/skha...,Honorary Professors,Algebraic Number Theory and Valuation Theory,"I am mainly interested in valuations, speciall...","Since 2017 : Emeritus Professor, Department of...",• Srinivasa Ramanujan Medal of Indian National...,...,"1978 - 1986: Lecturer , Dept. of Mathematics, ...",Yes,Yes,1973.0,1970s,Yes,8,27380,1075,60
129,Prof. Kapil Hari Paranjape,DMS,NaN,kapil,https://www.iisermohali.ac.in/faculty/dms/kapil,Emeritus Professors,"Algebraic Geometry, Algebraic Number Theory, A...",1. Construction of Algebraic Cycles as indicat...,2023 - 2025 : Member (Convenor for 2023 - 2024...,Fellowship of Indian Academy of Sciences Banga...,...,2023 - 2025: Member (Convenor for 2023 - 2024)...,Yes,Yes,1982.0,1980s,Yes,8,49811,1157,1600
130,Sohan Ghosh,DMS,NaN,NaN,NaN,Project Scientists,NaN,NaN,NaN,NaN,...,NaN,No,No,NaN,NaN,No,0,0,0,0

In [239]:
df_eda_done = pd.read_csv("faculty_eda_done.csv")

In [240]:
import sqlite3

conn = sqlite3.connect("iisermohali_faculty.db")

df_eda_done.to_sql(
    "faculty_clean",
    conn,
    if_exists="replace",
    index=False
)

conn.close()

print("Final faculty database saved!")

Final faculty database saved!